#############################################################################
# Makefile for building: TrikTest
# Generated by qmake (2.01a) (Qt 4.8.6) on: ?? ??? 19 19:27:08 2015
# Project:  TrikTest.pro
# Template: app
# Command: /opt/trik-sdk/sysroots/i686-oesdk-linux/usr/bin/qmake -o Makefile TrikTest.pro
#############################################################################

####### Compiler, tools and options

CC            = $(OE_QMAKE_CC)
CXX           = $(OE_QMAKE_CXX)
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -pipe $(OE_QMAKE_CFLAGS) -O2 -Wall -W -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -pipe -pipe $(OE_QMAKE_CFLAGS) $(OE_QMAKE_CXXFLAGS) -O2 -O2 -Wall -W -Wall -W -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/linux-g++ -I. -I$(OE_QMAKE_INCDIR_QT)/QtCore -I$(OE_QMAKE_INCDIR_QT)/QtNetwork -I$(OE_QMAKE_INCDIR_QT)/QtGui -I$(OE_QMAKE_INCDIR_QT) -I. -I../trikRuntime/trikControl/include -I/home/captain/rikRuntime/trikKernel/include -I.
LINK          = $(OE_QMAKE_LINK)
LFLAGS        = $(OE_QMAKE_LDFLAGS) -Wl,-O2,-rpath,. -Wl,-rpath-link,$(OE_QMAKE_LIBDIR_QT)
LIBS          = $(SUBLIBS)  -L$(OE_QMAKE_LIBDIR_QT) -L/home/captain/trikRuntime/bin/arm-release -ltrikControl -ltrikKernel -lqslog -lQtGuiE -lQtNetworkE -lQtCoreE -lpthread 
AR            = $(OE_QMAKE_AR) cqs
RANLIB        = 
QMAKE         = /opt/trik-sdk/sysroots/i686-oesdk-linux/usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = $(OE_QMAKE_STRIP)
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		test.cpp moc_test.cpp
OBJECTS       = main.o \
		test.o \
		moc_test.o
DIST          = /opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/common/unix.conf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/common/linux.conf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/common/gcc-base.conf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/common/gcc-base-unix.conf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/common/g++-unix.conf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/qconfig.pri \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/modules/qt_webkit_version.pri \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt_functions.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt_config.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/exclusive_builds.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/default_pre.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/release.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/default_post.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/shared.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/warn_on.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/unix/thread.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/moc.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/resources.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/uic.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/yacc.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/lex.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/include_source_dir.prf \
		TrikTest.pro
QMAKE_TARGET  = TrikTest
DESTDIR       = 
TARGET        = TrikTest

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: TrikTest.pro  /opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/linux-g++/qmake.conf /opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/common/unix.conf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/common/linux.conf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/common/gcc-base.conf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/common/gcc-base-unix.conf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/common/g++-unix.conf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/qconfig.pri \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/modules/qt_webkit_version.pri \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt_functions.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt_config.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/exclusive_builds.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/default_pre.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/release.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/default_post.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/shared.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/warn_on.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/unix/thread.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/moc.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/resources.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/uic.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/yacc.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/lex.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/include_source_dir.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/lib/libQtGuiE.prl \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/lib/libQtNetworkE.prl \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/lib/libQtCoreE.prl
	$(QMAKE) -o Makefile TrikTest.pro
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/common/unix.conf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/common/linux.conf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/common/gcc-base.conf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/common/gcc-base-unix.conf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/common/g++-unix.conf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/qconfig.pri:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/modules/qt_webkit_version.pri:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt_functions.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt_config.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/exclusive_builds.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/default_pre.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/release.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/default_post.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/shared.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/warn_on.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/unix/thread.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/moc.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/resources.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/uic.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/yacc.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/lex.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/include_source_dir.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/lib/libQtGuiE.prl:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/lib/libQtNetworkE.prl:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/lib/libQtCoreE.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile TrikTest.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/TrikTest1.0.0 || $(MKDIR) .tmp/TrikTest1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/TrikTest1.0.0/ && $(COPY_FILE) --parents test.h .tmp/TrikTest1.0.0/ && $(COPY_FILE) --parents main.cpp test.cpp .tmp/TrikTest1.0.0/ && (cd `dirname .tmp/TrikTest1.0.0` && $(TAR) TrikTest1.0.0.tar TrikTest1.0.0 && $(COMPRESS) TrikTest1.0.0.tar) && $(MOVE) `dirname .tmp/TrikTest1.0.0`/TrikTest1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/TrikTest1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_test.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_test.cpp
moc_test.cpp: test.h
	$(OE_QMAKE_MOC) $(DEFINES) $(INCPATH) test.h -o moc_test.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp test.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

test.o: test.cpp test.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o test.o test.cpp

moc_test.o: moc_test.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_test.o moc_test.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

